### PR TITLE
Update

### PR DESCRIPTION
**Pull request by yoshuawuyts**
- creates performance entries for idle timings
- fixes references in docs & package.json to choojs org
- adds `nanoassert` as a dep to be used in browsers instead of assert

### CODE REVIEW

**Review by jasonLaster — APPROVED** [review]
Looks good to me!

**Comment by yoshuawuyts** [comment]
We _definitely_ shouldn't land this, as there's too many modules that require this code to be inlined. What I think we should do instead, is create a new module – `timed-on-idle` that exposes this API. That way userland code can rely on the new package, while modules can keep relying on the existing code – all with a better chance of deduping too! :grin:

**Comment by yoshuawuyts** [comment]
It's really dope to see labels on rics tho

screen shot 2017-10-06 at 11 11 37

**Comment by yoshuawuyts** [comment]
Updated again, so only a few of the lesser changes are part of it. Removed the `nanotiming` stuff! :grin:

**Pull request merged**
